configs:
  cm:
    %{~ for i in range(count-students) ~}
    accounts.${studentname-prefix}${i+1}: "apiKey, login"
    %{~ endfor ~}
  secret:
    extra:
      %{~ for i in range(count-students) ~}
      accounts.${studentname-prefix}${i+1}.password: "${password_bcrypts[i]}"
      accounts.${studentname-prefix}${i+1}.passwordMtime: "1970-01-01T00:00:00Z"
      %{~ endfor ~}
