---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: songlaa-wildcard
  namespace: cert-manager
spec:
  secretName: songlaa-wildcard
  dnsNames:
  - "*.training.cluster.songlaa.com"
  issuerRef:
    name: letsencrypt-prod-songlaa
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: certificate-wildcard=true