---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-clusterrole
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/cilium-clusterrole
    repoURL: https://github.com/verysonglaa/songlaa-terraform-k8s-cluster-lab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true