---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/external-secrets/base
    repoURL: https://github.com/verysonglaa/songlaa-terraform-k8s-cluster-lab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true