---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: verysonglaa@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: haproxy
---
## Secret for Cloudflare API Token (this is created by terraform)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-secret
# type: Opaque
# stringData:
#   api-token: 1234567890
# ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-songlaa
spec:
  acme:
    email: verysonglaa@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-songlaa
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
