controller:
  kind: Deployment
  replicaCount: 3

  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"

  ingressClassResource:
    default: true
    enabled: true
    
  publishService:
    enabled: true

  extraArgs:
    default-ssl-certificate: cert-manager/songlaa-wildcard

  metrics:
    enabled: false

  serviceMonitor:
    enabled: false

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
    #add annotation for external-dns (cloudflare) to create a A record for *.training.cluster.songlaa.com
      external-dns.alpha.kubernetes.io/hostname: "*.training.cluster.songlaa.com"
    # add annotation for hetzner cloud to disable private ingress
      load-balancer.hetzner.cloud/disable-private-ingress: 'true'
      

