controller:
  kind: Deployment
  replicaCount: 3

  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    value: "true"
    effect: "NoSchedule"

  ingressClassResource:
    default: true
    enabled: true

  extraArgs:
    default-ssl-certificate: cert-manager/songlaa-wildcard

  metrics:
    enabled: true

  serviceMonitor:
    enabled: false

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster