# creates the secret for the webshell (because it is not part of the helm chart)
# probably not needed for the webshell (replaced by webshell-basic-auth), delete when you have time
apiVersion: v1
data:
  username: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
kind: Secret
metadata:
  labels:
    acend-userconfig: "true"
  namespace: {{ .Values.user }}
  name: acend-userconfig
type: Opaque
