# creates the secret for the webshell (because it is not part of the helm chart)
# and holds the user credentials for read by scripts
apiVersion: v1
data:
  username: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
kind: Secret
metadata:
  labels:
    acend-userconfig: "true"
  namespace: {{ .Values.user }}
  name: acend-userconfig
type: Opaque
